env:
  browser: true
  es6: true
  node: true
extends:
  - google
  - plugin:react/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  "require-jsdoc": 0,
  "comma-dangle": 0,
  "max-len": [2, {"code": 100}]
}
